[2023-05-09T04:55:24.724+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: veryfi_extract_total.extract_and_load manual__2023-05-09T04:55:23.525993+00:00 [queued]>
[2023-05-09T04:55:24.731+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: veryfi_extract_total.extract_and_load manual__2023-05-09T04:55:23.525993+00:00 [queued]>
[2023-05-09T04:55:24.731+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-09T04:55:24.739+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): extract_and_load> on 2023-05-09 04:55:23.525993+00:00
[2023-05-09T04:55:24.744+0000] {standard_task_runner.py:57} INFO - Started process 1498 to run task
[2023-05-09T04:55:24.748+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'veryfi_extract_total', 'extract_and_load', 'manual__2023-05-09T04:55:23.525993+00:00', '--job-id', '390', '--raw', '--subdir', 'DAGS_FOLDER/ml_response_dag.py', '--cfg-path', '/tmp/tmpkn7xr2rb']
[2023-05-09T04:55:24.748+0000] {standard_task_runner.py:85} INFO - Job 390: Subtask extract_and_load
[2023-05-09T04:55:24.804+0000] {task_command.py:410} INFO - Running <TaskInstance: veryfi_extract_total.extract_and_load manual__2023-05-09T04:55:23.525993+00:00 [running]> on host aa4b7d3de44b
[2023-05-09T04:55:24.897+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='veryfi_extract_total' AIRFLOW_CTX_TASK_ID='extract_and_load' AIRFLOW_CTX_EXECUTION_DATE='2023-05-09T04:55:23.525993+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-09T04:55:23.525993+00:00'
[2023-05-09T04:55:24.908+0000] {ml_response_dag.py:35} INFO - {}
[2023-05-09T04:55:24.908+0000] {ml_response_dag.py:36} INFO - 1
[2023-05-09T04:55:24.908+0000] {ml_response_dag.py:37} INFO - Inserted to db
[2023-05-09T04:55:24.909+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_response_dag.py", line 38, in extract_total
    value = int(total.get('value'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2023-05-09T04:55:24.921+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=veryfi_extract_total, task_id=extract_and_load, execution_date=20230509T045523, start_date=20230509T045524, end_date=20230509T045524
[2023-05-09T04:55:24.935+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 390 for task extract_and_load (int() argument must be a string, a bytes-like object or a number, not 'NoneType'; 1498)
[2023-05-09T04:55:24.960+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-09T04:55:24.978+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
